version: '2'
services:
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "5140:5140"

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9350:9350"

  mongo:
    image: "mongo:3"

  graylog:
    build: ./graylog
    ports:
      - "9000:9000"
      - "1514:1514/udp"
      - "12201:12201/udp"
      - "12900:12900"
    links:
      - elasticsearch
      - mongo
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api

  app:
    restart: always
    build: .
    ports:
      - "4000:8082"
      - "4003:50051"
    networks:
      - test_net
    depends_on:
      - fluentd
    environment:
      - DEBUG
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: docker

  client:
    container_name: app_order_client
    restart: always
    build: ./client
    ports:
      - "4001:8081"
    networks:
      - test_net
    environment:
      - DEBUG
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: docker

networks:
  test_net:
    driver: bridge