server:
  port: 8082
spring:
  application:
    name: order_verify
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        order-verify-request:
          destination: orderVerifyRequest
          contentType: application/json
          group: requestProducer
        order-verify-response:
          destination: orderVerifyResponse
          contentType: application/json
          group: responseConsumer
  datasource:
    url: jdbc:mysql://host.docker.internal:8889/test_springboot_stream?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    user:
      name: client1
      password: password
      roles: USER
  redis:
    host: host.docker.internal
    port: 6379
grpc:
  port: 50051
#  security:
#    cert-chain: file:../order/ssl/server.crt
#    private-key: file:../order/ssl/server.pem

